USE [D:\EMPREGO\BK\FI.WEBATIVIDADEENTREVISTA\FI.WEBATIVIDADEENTREVISTA\APP_DATA\BANCODEDADOS.MDF]
GO
/****** Object:  StoredProcedure [dbo].[FI_SP_IncBeneficiario]    Script Date: 26/10/2024 00:14:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROC [dbo].[FI_SP_IncBeneficiario]
    @NOME          VARCHAR (50) ,
	@CPF           VARCHAR (14)  ,
    @IDCLIENTE     BIGINT
AS
BEGIN
	INSERT INTO BRBENEFICIARIOS(NOME, CPF, IDCLIENTE) 
	VALUES (@NOME, @CPF, @IDCLIENTE)

	SELECT SCOPE_IDENTITY()
END